### ISSUE TITLE
Build no run

### ISSUE THREAD

**Issue by duongvuhd** [voun-github/Video_Sub_Extractor#1]
build successfully without any errors but cannot run, please help

https://github.com/voun-github/Video_Sub_Extractor/assets/105042149/6b150dc8-0343-4383-80d5-74a8bae774a7

**Comment by duongvuhd** [comment]
![image](https://github.com/voun-github/Video_Sub_Extractor/assets/105042149/9b8ff4ba-e6d8-40f2-af7d-d1bc2f1d15a6)

**Comment by voun-github** [comment]
@duongvuhd sorry for the late reply. Because of the paddle program, compiling the app is error-prone. I am currently implementing another ocr program with pytorch that will be used to replace paddle.
